import { intro, log, outro } from '@clack/prompts';
import { compile } from 'json-schema-to-typescript';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import pc from 'picocolors';

type CliArgs = {
  help: boolean;
  searchRoot: string;
  stamp: string;
  verbose: boolean;
};

type CollectionSchematicEntry = { schema?: string };

type ErrnoLike = NodeJS.ErrnoException;

type SchematicCollectionFile = {
  schematics?: Record<string, CollectionSchematicEntry>;
};

function isErrnoException(error: unknown): error is ErrnoLike {
  return Boolean(
    error &&
    typeof error === 'object' &&
    'code' in error &&
    typeof error.code === 'string'
  );
}

const repoRoot = process.cwd();
const defaultSearchRoot = path.join(repoRoot, 'packages');

function parseCliArgs(argv: string[]): CliArgs {
  const args = [...argv];
  let stamp = '';
  let verbose = true;
  let help = false;
  const positional: string[] = [];

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];

    if (arg.startsWith('--stamp=')) {
      stamp = arg.slice('--stamp='.length);
      continue;
    }

    if (arg === '--stamp') {
      stamp = args[i + 1] ?? '';
      i += 1;
      continue;
    }

    if (arg === '--no-verbose') {
      verbose = false;
      continue;
    }

    if (arg === '--help' || arg === '-h') {
      help = true;
      continue;
    }

    positional.push(arg);
  }

  return {
    help,
    searchRoot: path.resolve(positional[0] ?? defaultSearchRoot),
    stamp,
    verbose,
  };
}

const cli = parseCliArgs(process.argv.slice(2));

if (cli.stamp && !isValidDirectorySegment(cli.stamp)) {
  log.error(
    [
      `Stamp must be a valid file segment, which "${cli.stamp}" is not`,
      'see https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry',
    ].join('\n')
  );

  process.exit(1);
}

const searchRoot = cli.searchRoot;

const header = `// THIS FILE IS AUTOMATICALLY GENERATED.
// Update the corresponding schema.json file, then rerun the generator.

`;

async function discoverSchemaPaths(rootDir: string): Promise<string[]> {
  const collectionFiles = await findFiles(rootDir, 'collection.json');
  const discovered: Set<string> = new Set();

  for (const collectionPath of collectionFiles) {
    for (const schemaPath of await schemaPathsFromCollection(collectionPath)) {
      discovered.add(schemaPath);
    }
  }

  if (discovered.size > 0) {
    return [...discovered].sort();
  }

  const schemaFiles = await findFiles(rootDir, 'schema.json');
  return schemaFiles.sort();
}

async function findFiles(rootDir: string, fileName: string): Promise<string[]> {
  try {
    const allFiles = await walk(rootDir);
    return allFiles.filter((filePath) => path.basename(filePath) === fileName);
  } catch (error) {
    if (isErrnoException(error) && error.code === 'ENOENT') {
      return [];
    }

    throw error;
  }
}

async function generateTypes(schemaPath: string): Promise<string> {
  const schema = JSON.parse(await fs.readFile(schemaPath, 'utf8'));
  const generated = await compile(schema, 'Options', {
    bannerComment: '',
    style: {
      singleQuote: true,
    },
  });

  return `${header}${normalizeTopLevelName(generated.trim())}\n`;
}

function isValidDirectorySegment(name: string): boolean {
  // 1. Reject empty inputs or purely whitespace names
  if (!name || !name.trim()) {
    return false;
  }

  // 2. Strict Whitelist: Only allow letters, numbers, underscores, and hyphens.
  // This explicitly blocks dots (.), slashes (/ or \), and structural text.
  const strictSegmentPattern = /^[a-zA-Z0-9_-]+$/;
  if (!strictSegmentPattern.test(name)) {
    return false;
  }

  // 3. Block Windows reserved system names (case-insensitive)
  const windowsReservedPattern = /^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])$/i;
  if (windowsReservedPattern.test(name)) {
    return false;
  }

  // 4. Enforce standard OS single-segment length limits
  if (name.length > 255) {
    return false;
  }

  return true;
}

async function main(): Promise<void> {
  if (cli.help) {
    console.log(
      `Usage: node tools/generate-schema-types.ts [search-root] [--stamp <name>] [--verbose]\n`
    );
    return;
  }

  intro(pc.cyan('Generate schema TypeScript types'));

  log.step(
    `Scanning ${path.relative(repoRoot, searchRoot) || '.'} for schema.json files...`
  );

  const schemaPaths = await discoverSchemaPaths(searchRoot);

  if (schemaPaths.length === 0) {
    outro(
      pc.yellow(
        `No schema.json files found under ${path.relative(repoRoot, searchRoot) || '.'}.`
      )
    );
    return;
  }

  log.step(`Generating from ${schemaPaths.length} schema file(s)...`);

  let updatedCount = 0;

  for (const schemaPath of schemaPaths) {
    const parsed = path.parse(schemaPath);
    const fileName = cli.stamp
      ? `${parsed.name}.${cli.stamp}.generated.ts`
      : `${parsed.name}.generated.ts`;
    const outputPath = path.join(parsed.dir, fileName);
    const generated = await generateTypes(schemaPath);
    const changed = await writeIfChanged(outputPath, generated);

    const relativeOutput = path.relative(repoRoot, outputPath);
    if (changed) {
      updatedCount += 1;
      if (cli.verbose) {
        log.success(`${pc.green('updated')} ${relativeOutput}`);
      }
    } else if (cli.verbose) {
      log.warn(`${pc.gray('unchanged')} ${relativeOutput}`);
    }
  }

  log.success(
    // pc.green(
    `Processed ${schemaPaths.length} schema file(s); updated ${updatedCount}.`
    // )
  );

  if (cli.stamp) {
    outro(pc.cyan(`Done. Output suffix: .${cli.stamp}.generated.ts`));
    return;
  }

  outro(pc.cyan('Done. Output suffix: .generated.ts'));
}

function normalizeTopLevelName(sourceText: string): string {
  return sourceText.replace(
    /^export (interface|type) \w+\b/m,
    'export $1 Options'
  );
}

async function schemaPathsFromCollection(
  collectionPath: string
): Promise<string[]> {
  const raw = await fs.readFile(collectionPath, 'utf8');
  const parsed: SchematicCollectionFile = JSON.parse(raw);
  const schematics = parsed.schematics ?? {};
  const collectionDir = path.dirname(collectionPath);
  const schemaPaths: string[] = [];

  for (const schematic of Object.values(schematics)) {
    if (!schematic || typeof schematic !== 'object') {
      continue;
    }

    const { schema } = schematic;
    if (typeof schema === 'string') {
      schemaPaths.push(path.resolve(collectionDir, schema));
    }
  }

  return schemaPaths;
}

async function walk(dirPath: string): Promise<string[]> {
  const entries = await fs.readdir(dirPath, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    if (
      entry.name === 'node_modules' ||
      entry.name === 'dist' ||
      entry.name === '.git'
    ) {
      continue;
    }

    const entryPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await walk(entryPath)));
    } else {
      files.push(entryPath);
    }
  }

  return files;
}

async function writeIfChanged(
  filePath: string,
  nextContent: string
): Promise<boolean> {
  let currentContent = null;
  try {
    currentContent = await fs.readFile(filePath, 'utf8');
  } catch (error) {
    if (!isErrnoException(error) || error.code !== 'ENOENT') {
      throw error;
    }
  }

  if (currentContent === nextContent) {
    return false;
  }

  await fs.writeFile(filePath, nextContent, 'utf8');
  return true;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
